server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_shiro
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
  http:
    encoding:
      charset: utf-8
      enabled: true
  redis:
    shiro:
      host: localhost
      port: 6379
      password: 
      timeout: 0